export { default as typescript } from './configs/typescript.js'
export { default as prettier } from './configs/prettier.js'
export { default as commonjs } from './configs/commonjs.js'
export { default as esm } from './configs/esm.js'
export { default as imports } from './configs/imports.js'
export * as ignores from './configs/ignores.js'
